package no.runsafe.survivalchallenge;

public enum Objective
{
	CRAFT_WORKBENCH,
	DIAMONDS,
	EMERALDS,
	VIlLAGER_TRADE,
	ENDERMAN_KILL,
	ZOMBIE_KILL,
	CREEPER_KILL,
	SKELETON_KILL,
	SILVERFISH_KILL,
	SLIME_KILL,
	SPIDER_KILL,
	CAVE_SPIDER_KILL,
	DIAMOND_ARMOUR,
	ENCHANT_ITEM,
	TAME_SOMETHING,
	CREEPER_SNIPE,
	SNOWBALL_AT_SQUID,
}
